# Generated by Django 3.1.3 on 2020-11-15 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('code', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
                ('who_region', models.CharField(max_length=5)),
                ('continent', models.CharField(max_length=20)),
                ('is_island', models.BooleanField()),
                ('political_view', models.CharField(max_length=15)),
                ('gdp', models.DecimalField(decimal_places=2, max_digits=9)),
                ('free_healthcare', models.BooleanField()),
                ('religion', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Date',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('weekday', models.CharField(choices=[('MO', 'Monday'), ('TU', 'Tuesday'), ('WE', 'Wednesday'), ('TH', 'Thursday'), ('FR', 'Friday'), ('SA', 'Saturday'), ('SU', 'Sunday')], max_length=2)),
                ('month', models.CharField(choices=[('JAN', 'January'), ('FEB', 'February'), ('MAR', 'Mars'), ('APR', 'April'), ('MAY', 'May'), ('JUN', 'June'), ('JUL', 'July'), ('AUG', 'August'), ('SEP', 'September'), ('OCT', 'October'), ('NOV', 'November'), ('DEC', 'December')], max_length=3)),
                ('year', models.PositiveSmallIntegerField()),
                ('quarter', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='WhoData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_reported', models.DateField()),
                ('new_cases', models.PositiveIntegerField()),
                ('cumulative_cases', models.PositiveIntegerField()),
                ('new_deaths', models.PositiveIntegerField()),
                ('cumulative_deaths', models.PositiveIntegerField()),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='who_data.country')),
            ],
        ),
        migrations.CreateModel(
            name='CalculatedData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('population', models.PositiveIntegerField()),
                ('percentage_positive', models.PositiveSmallIntegerField()),
                ('positive_100_000', models.PositiveIntegerField()),
                ('deaths_100_000', models.PositiveIntegerField()),
                ('country_code', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='who_data.country')),
            ],
        ),
    ]
