# Generated by Django 3.1.3 on 2020-12-06 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('who_data', '0004_auto_20201205_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whodata',
            name='country',
            field=models.CharField(max_length=100),
        ),
    ]
