version: "3.9"
services:
  db:
    image: postgres:latest
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=covid_project1
      - POSTGRES_USER=usercovid
      - POSTGRES_PASSWORD=Secretpassword
  web:
    image: valentinrault/covid:compose-1
    command: python covid_project/manage.py runserver 0.0.0.0:8000
    # volumes:
    #  - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
